import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicShell } from "@/components/PublicSiteShell";
import { Breadcrumbs, Byline, Faqs, JsonLd, RecordCta } from "@/components/seo/Editorial";
import { nationalGuides, getNationalGuide } from "@/lib/national-guides";
import { getStateGuide } from "@/lib/state-guides";
import { articleSchema, pageMetadata } from "@/lib/seo";
export const dynamicParams = false;
export function generateStaticParams() { return nationalGuides.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const guide = getNationalGuide(slug); return guide ? pageMetadata(`${guide.title} | ClearCME`, guide.description, `/guides/${slug}`) : { robots: { index: false } }; }
export default async function GuidePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const guide = getNationalGuide(slug); if (!guide) notFound();
  return <PublicShell><article className="mx-auto max-w-3xl space-y-10 px-6 py-12"><JsonLd data={articleSchema(guide.title, `/guides/${slug}`)} /><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "CME requirements", href: "/cme-requirements" }, { label: guide.title, href: `/guides/${slug}` }]} /><header><div className="public-kicker mb-5">A practical physician guide</div><h1 className="public-heading text-4xl sm:text-5xl">{guide.title}</h1><p className="public-subhead mt-6">{guide.description}</p><Byline verified="2026-09-18" modified="2026-09-18" /></header>{guide.sections.map((section) => <section key={section.title}><h2 className="public-heading text-3xl mb-4">{section.title}</h2>{section.paragraphs.map((p) => <p key={p} className="mt-4 leading-7 text-[#3f4a40]">{p}</p>)}</section>)}<section><h2 className="public-heading text-3xl mb-5">Check the rules behind the plan</h2><p className="mb-4 leading-7">These state guides link to the primary board sources for the examples above. Current board rules and individual approvals control.</p><ul className="space-y-3">{guide.relatedStates.map((slug) => <li key={slug}><Link className="font-semibold underline" href={`/cme-requirements/${slug}`}>{getStateGuide(slug)?.name} requirements and sources →</Link></li>)}<li><Link className="font-semibold underline" href="/mate-act">Federal DEA MATE Act guide and source →</Link></li><li><Link className="font-semibold underline" href="/courses/opioid-prescribing">Opioid CME course library →</Link></li><li><Link className="font-semibold underline" href="/courses/human-trafficking">Human-trafficking course library →</Link></li></ul></section><Faqs items={guide.faqs} /><RecordCta note="Keep your licenses, certificates and completion history together. Review extracted information and any unresolved requirement details before relying on a status or making an official attestation." /><section><h2 className="public-heading text-3xl mb-5">Continue your CME plan</h2><ul className="space-y-3">{nationalGuides.filter((item) => item.slug !== slug).map((item) => <li key={item.slug}><Link className="underline underline-offset-4" href={`/guides/${item.slug}`}>{item.title} →</Link></li>)}</ul></section></article></PublicShell>;
}
