import Link from "next/link";
import { PublicShell } from "@/components/PublicSiteShell";
import { Breadcrumbs, Byline, Faqs, JsonLd, RecordCta } from "@/components/seo/Editorial";
import { articleSchema } from "@/lib/seo";

const source = "https://www.deadiversion.usdoj.gov/faq/MATE_Act_faq.html";
const faqs = [
  { question: "Is the DEA MATE Act eight hours every renewal?", answer: "No. It is a one-time training/qualification attestation at your first applicable DEA registration or renewal on or after June 27, 2023. It is not a new eight-hour obligation at each later renewal." },
  { question: "Can previous training count?", answer: "Yes, qualifying past training can count. DEA says it does not have to be newly completed after the law’s enactment. Check the eligible training organization, required subject matter and your supporting records." },
  { question: "Must I take one eight-hour course?", answer: "No. DEA permits the eight hours to be accumulated across qualifying training. Keep each certificate and enough detail to establish the combined hours and content." },
  { question: "Who can qualify without buying another course?", answer: "DEA identifies qualifying addiction board certifications and recent graduates with qualifying education, in addition to the training pathway. Check the exact certification, graduation timing and curriculum against the DEA FAQ before relying on a deemed-complete pathway." },
  { question: "Does the requirement apply if I only prescribe Schedule III–V drugs?", answer: "DEA’s requirement applies to covered practitioners registering to dispense controlled substances in Schedules II–V; it is not limited to Schedule II prescribing. Practitioners who are solely veterinarians are excluded." },
  { question: "Does MATE training replace my state’s opioid CME?", answer: "No automatic substitution applies. A course may serve both purposes only when it independently satisfies the state’s content, approval, timing and category requirements. Read your state guide and verify the specific activity." },
  { question: "Does ClearCME make the DEA attestation for me?", answer: "No. ClearCME lets you keep your federal training record alongside your state CME records. You make the official attestation in the DEA registration process and remain responsible for its accuracy." },
];
export default function MateActPage() {
  return <PublicShell><article className="mx-auto max-w-3xl space-y-10 px-6 py-12">
    <JsonLd data={articleSchema("DEA MATE Act: the 8-hour training requirement", "/mate-act", "2026-09-18", "2026-04-13")} />
    <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "DEA MATE Act", href: "/mate-act" }]} />
    <header><div className="public-kicker mb-5">Federal training · one-time requirement</div><h1 className="public-heading text-4xl sm:text-6xl">DEA MATE Act: the 8-hour training requirement</h1><p className="public-subhead mt-6">How physicians and other covered DEA registrants can satisfy the training requirement, document an eligible pathway and make the required attestation.</p><Byline verified="2026-09-18" modified="2026-09-18" published="2026-04-13" /></header>
    <section className="public-card p-7"><h2 className="public-heading text-3xl mb-4">Start with your first applicable DEA registration</h2><p className="leading-7">The requirement applies at the first DEA registration or renewal on or after June 27, 2023. Covered practitioners must attest to a qualifying training or education pathway. It is one-time, and practitioners who are solely veterinarians are excluded.</p><p className="mt-4 leading-7">Your current DEA expiration date may not identify that first event. Review your registration history and retain evidence of the pathway you used.</p><a className="mt-4 inline-block text-sm underline" href={source}>Source: DEA MATE Act questions and answers ↗</a></section>
    <section><h2 className="public-heading mb-5 text-3xl">Three ways physicians may meet the requirement</h2><ol className="list-decimal space-y-5 pl-5 leading-7"><li><strong>Qualifying training.</strong> Complete at least eight hours of eligible training on treating and managing patients with opioid or other substance use disorders through a recognized organization. DEA permits a single course or accumulated qualifying sessions.</li><li><strong>Qualifying addiction certification.</strong> DEA identifies specified addiction medicine or addiction psychiatry certifications, including its listed ABMS, ABAM and AOA pathways. Match your actual credential to the DEA language.</li><li><strong>Qualifying recent education.</strong> DEA describes a pathway for recent graduates of accredited U.S. professional schools who completed the required curriculum. Confirm the applicable five-year graduation window and curriculum documentation using the current DEA instructions.</li></ol><p className="mt-5 text-sm leading-6">The detailed pathways differ for physicians and other practitioners. <a className="underline" href={source}>Read the DEA’s complete eligibility criteria</a> before attesting.</p></section>
    <section><h2 className="public-heading text-3xl mb-5">How to satisfy and document it</h2><ol className="list-decimal space-y-3 pl-5 leading-7"><li>Check whether prior qualifying training or a deemed-complete pathway already applies.</li><li>If training remains, verify the provider, subject matter and hours before enrolling.</li><li>Save completion certificates or education/certification evidence with your federal training record.</li><li>Complete the official attestation during the DEA registration process. Recording it in ClearCME is a separate organizational step.</li></ol><div className="mt-6 flex flex-wrap gap-4"><Link href="/courses/substance-use" className="public-btn-secondary">Explore MATE/SUD courses →</Link><Link href="/courses/opioid-prescribing" className="public-btn-secondary">Opioid prescribing courses →</Link></div><p className="mt-4 text-sm leading-6 text-[#596650]">Prices and activity approvals can change. Confirm the current provider page; a related course topic alone is not proof of MATE eligibility.</p></section>
    <section><h2 className="public-heading mb-4 text-3xl">State requirements still apply</h2><p className="leading-7">One activity can be relevant to several requirements, but state topic clocks and provider approvals remain separate. Review <Link className="underline" href="/cme-requirements/texas">Texas</Link>, <Link className="underline" href="/cme-requirements/florida">Florida</Link>, <Link className="underline" href="/cme-requirements/new-york">New York</Link>, <Link className="underline" href="/cme-requirements/california">California</Link> or <Link className="underline" href="/cme-requirements/nevada">Nevada</Link>, or <Link className="underline" href="/cme-requirements">browse the state hub</Link>.</p></section>
    <Faqs items={faqs} />
    <RecordCta note="Keep your training certificates and qualifying-pathway record together with your state CME records. Check your first applicable DEA registration date and complete the official attestation with DEA." />
    <section><h2 className="public-heading mb-4 text-3xl">Primary source and verification</h2><a className="font-semibold underline" href={source}>DEA Diversion Control Division · MATE Act Q&amp;A ↗</a><blockquote className="my-4 border-l-2 border-[#bfd1ad] pl-4">“It should be noted that this is a one-time attestation”</blockquote><p className="text-sm leading-6">September 18, 2026: checked the first applicable registration deadline, one-time nature, eligible pathways and aggregated-training guidance against DEA’s current FAQ. The verification date is a content check, not a new regulatory effective date.</p></section>
  </article></PublicShell>;
}
