import Link from "next/link";
import { PublicShell } from "@/components/PublicSiteShell";
import { Breadcrumbs } from "@/components/seo/Editorial";
import { StateDirectory } from "@/components/seo/StateDirectory";
import { STATE_OPTIONS } from "@/lib/state-requirements";
import { publishedStateGuides } from "@/lib/state-guides";
import { AUTHOR_PATH, pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("Physician CME Requirements by State — MD & DO | ClearCME", "Browse all 50 states and DC. Read verified physician CME guides with MD/DO differences, mandatory topics, renewal cycles and primary board sources.", "/cme-requirements");
export default function RequirementsHub() {
  const states = STATE_OPTIONS.map((state) => { const guide = publishedStateGuides.find((guide) => guide.code === state.code); return { code: state.code, name: state.name, slug: guide?.slug ?? null, boardLabel: guide ? (guide.boards.length > 1 ? "MD and DO rules differ" : "MD and DO physician guide") : "Check the board for your license type" }; });
  return <PublicShell><div className="mx-auto max-w-6xl px-6 py-12"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "CME requirements", href: "/cme-requirements" }]} /><header className="max-w-3xl py-10"><div className="public-kicker mb-5">50 states + Washington, DC</div><h1 className="public-heading text-4xl sm:text-6xl">Physician CME requirements by state</h1><p className="public-subhead mt-6">Find the rules behind your next renewal. Start with your state, then check your license type, mandatory topics and course categories.</p><p className="mt-5 text-sm leading-7 text-[#596650]">Physician author: <Link className="underline" href={AUTHOR_PATH}>Michael Rushton, DO</Link>. Each published guide shows its verification date and primary sources. <Link href="/methodology" className="underline">How we verify requirements →</Link></p></header><StateDirectory states={states} /><section className="mt-14 max-w-3xl space-y-5"><h2 className="public-heading text-3xl">Why the requirements differ</h2><p className="leading-7">States set their own hours, accepted accreditation, reporting windows and mandatory topics. Separate medical and osteopathic boards may use different rules. Your specialty, prescribing authority, issue date and prior training can change what applies.</p><p className="leading-7">A general-hour total is a starting point. Read the topic-specific clocks, first-renewal exceptions and official reporting instructions. Federal DEA training runs alongside those state rules.</p><div className="flex flex-wrap gap-5 font-semibold text-[#3f5f33]"><Link href="/mate-act">DEA MATE Act →</Link><Link href="/guides/multi-state-cme-requirements">Multi-state planning →</Link><Link href="/physician-cme-tracker">Physician CME tracker →</Link></div></section></div></PublicShell>;
}
