export type Course = {
  name: string;
  provider: string;
  providerUrl: string;
  credits: string;
  creditType: string;
  price: string;
  isFree: boolean;
  isHippo: boolean;
  description: string;
  url: string;
  // Optional Scout-sourced metadata
  accreditation?: string;
  deaMateCompliant?: boolean;
  stateAcceptance?: string;
  verified?: string;
};

export type TopicCatalog = {
  topicLabel: string;
  requirement: string;
  courses: Course[];
};

export const COURSE_CATALOG: Record<string, TopicCatalog> = {
  SUBSTANCE_USE: {
    topicLabel: "DEA MATE Act / SUD Treatment",
    requirement: "8 hours, one-time (DEA-registered physicians)",
    courses: [
    // Auto-synced from Scout catalog — 2026-04-25T01:44:40.677Z
      {
        name: "POWER: Prevention of Opioid Misuse in Women through Education and Resource",
        provider: "FreeCME (by Relias)",
        providerUrl: "https://www.freecme.com",
        credits: "6 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Relias/FreeCME platform. Search \"POWER\" on freecme.com. 6-hour series focused on opioid misuse prevention in women. Requires free account.",
        url: "https://www.freecme.com/",
        accreditation: "ACCME",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-16",
      },
      {
        name: "Addiction Treatment and Care CME for Family Physicians",
        provider: "American Academy of Family Physicians (AAFP)",
        providerUrl: "https://www.aafp.org",
        credits: "3.75 AMA PRA Category 1 / AAFP Prescribed / AOA Category 2 equivalent",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Free on-demand CME for family physicians covering stigma, trauma-informed care, harm reduction, addiction neurobiology, and urine drug screen interpretation. Includes four modules and is supported by a SAMHSA educational grant. Approval term: 10/14/2025–10/14/2027.",
        url: "https://www.aafp.org/cme/all/addiction-treatment-and-care.html",
        accreditation: "ACCME (AAFP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; AAFP Prescribed credit accepted by AMA as equivalent to AMA PRA Category 1",
        verified: "2026-04-22",
      },
      {
        name: "Appropriate Use of Drug Testing in Clinical Addiction Medicine",
        provider: "American Society of Addiction Medicine (ASAM) eLearning",
        providerUrl: "https://elearning.asam.org",
        credits: "1 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Webinar-based CME covering ASAM's guidance document on appropriate drug testing in addiction medicine. Practical clinical skill for prescribers managing patients with SUD. Free for all including non-members. Register at elearning.asam.org → Free Sessions.",
        url: "https://elearning.asam.org/ (navigate to Free Sessions)",
        accreditation: "ACCME (ASAM — Accreditation with Commendation)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-18",
      },
      {
        name: "Screening for Alcohol, Tobacco, Cannabis and Polysubstance Use",
        provider: "American Academy of Family Physicians (AAFP)",
        providerUrl: "https://www.aafp.org",
        credits: "1 AAFP Prescribed / AMA PRA Category 1 equivalent / AOA Category 2 equivalent",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Free AAFP prenatal substance-use CME module focused on screening reproductive-age adults for alcohol, tobacco, cannabis, and polysubstance use. Includes SBIRT workflow/documentation context. Approval term: 9/18/2023–9/18/2026.",
        url: "https://www.aafp.org/cme/all/maternity/addressing-prenatal-alcohol-and-other-substance-use.html",
        accreditation: "ACCME (AAFP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; AAFP Prescribed credit accepted by AMA as equivalent to AMA PRA Category 1",
        verified: "2026-04-22",
      },
      {
        name: "Brief Intervention and Referral to Treatment for Alcohol, Tobacco, Cannabis, and Other Substance Use",
        provider: "American Academy of Family Physicians (AAFP)",
        providerUrl: "https://www.aafp.org",
        credits: "0.75 AAFP Prescribed / AMA PRA Category 1 equivalent / AOA Category 2 equivalent",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Free AAFP prenatal substance-use CME module covering brief intervention and referral to treatment (SBIRT) for alcohol, tobacco, cannabis, and other substance use in reproductive-age patients. Approval term: 9/18/2023–9/18/2026.",
        url: "https://www.aafp.org/cme/all/maternity/addressing-prenatal-alcohol-and-other-substance-use.html",
        accreditation: "ACCME (AAFP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; AAFP Prescribed credit accepted by AMA as equivalent to AMA PRA Category 1",
        verified: "2026-04-22",
      }
    ],
  },
  OPIOID_PRESCRIBING: {
    topicLabel: "Opioid Prescribing",
    requirement: "Varies by state (2-3 hrs, recurring)",
    courses: [
    // Auto-synced from Scout catalog — 2026-04-25T01:44:40.677Z
      {
        name: "Pain Management and Opioids CME",
        provider: "NEJM Group (formerly NEJM Knowledge+, now with AMBOSS)",
        providerUrl: "https://pain-management-cme.nejm.org",
        credits: "10.25 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "62 case-based questions across 8 focused topics. 50+ videos and infographics. PDF summaries. Progress tracking. Updated April 2026 — active and confirmed. Previously at knowledgeplus.nejm.org — new URL is pain-management-cme.nejm.org. Current approval window explicitly states AAFP Prescribed credit approval from 04/16/2026 to 04/15/2027. This no-cost 10.25-hour training satisfies the DEA's 8-hour requirement and may help with CDC safe prescribing compliance.",
        url: "https://pain-management-cme.nejm.org/",
        accreditation: "ACCME (Massachusetts Medical Society)",
        deaMateCompliant: true,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-21 (homepage + accreditation details reconfirmed live)",
      },
      {
        name: "Online 8-Hour SUD 101 Training",
        provider: "PCSS-MOUD (funded by SAMHSA)",
        providerUrl: "https://pcssnow.org",
        credits: "8 AMA PRA Category 1 / AAPA Category 1 / ANCC / ACPE / IPCE",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Comprehensive 8-module bundle covering SUD overview, assessment, and MOUD. Fulfills the full 8-hour federal requirement.",
        url: "https://pcssnow.org/medications-for-opioid-use-disorder/",
        accreditation: "ACCME / AAPA / ANCC / ACPE",
        deaMateCompliant: true,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-15",
      },
      {
        name: "Online 8-Hour Training: Pain, Opioids & Effective Patient Care",
        provider: "PCSS-MOUD",
        providerUrl: "https://pcssnow.org",
        credits: "8 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Flexible curriculum allowing users to pick 8 modules from 14 options in the Pain Core Curriculum.",
        url: "https://pcssnow.org/medications-for-opioid-use-disorder/",
        accreditation: "ACCME",
        deaMateCompliant: true,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-15",
      },
      {
        name: "Opioid and Substance Use Disorder CME/CE",
        provider: "Pri-Med",
        providerUrl: "https://www.pri-med.com",
        credits: "8 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Specifically designed for primary care providers to meet the MATE Act requirement.",
        url: "https://www.pri-med.com/online-education/opioid-sud-cme-center",
        accreditation: "ACCME",
        deaMateCompliant: true,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-15",
      },
      {
        name: "UCSF Addiction Medicine Online Course (DEA MATE Act Compliant)",
        provider: "University of California, San Francisco (UCSF) Office of CME",
        providerUrl: "https://ucsf.cloud-cme.com",
        credits: "8 AMA PRA Category 1 (+ AAPA Cat 1, ACPE, ABA MOCA Part 2, ABIM MOC Part 2, ABS CC, ABOHNS MOC, ABPath MOC, MATE Act Credits)",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Recorded from the 4th Annual UCSF Addiction CME Conference. 8 videos covering: SUD as a brain disease, methadone, buprenorphine inductions, stimulants and drug-involved deaths, hospital-based care, street medicine, pregnancy and SUD, adolescent addiction medicine. On-demand, self-paced. Course #MED27052. **⚠️ Expires July 31, 2026 — enroll now.** Cost is $75 (above our $30 low-cost threshold — cataloged as a premium paid option). UCSF OCME holds Joint Accreditation with Commendation — one of the most credentialed CME providers in the U.S. Ideal for EM physicians and hospitalists managing patients with SUD.",
        url: "https://ucsf.cloud-cme.com/course/courseoverview?P=0&EID=1318",
        accreditation: "ACCME (UCSF OCME — Joint Accreditation with Commendation, 2024)",
        deaMateCompliant: true,
        stateAcceptance: "All states accepting AMA PRA Category 1. CA AB 487 Pain Management credit included. AAPA Cat 1 for PAs (valid through June 30, 2026).",
        verified: "2026-04-19",
      },
      {
        name: "Free DEA MATE Act Training — 8 Hours CME (3 Courses)",
        provider: "RxCE.com",
        providerUrl: "https://rxce.com",
        credits: "8 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "3 free on-demand courses totaling 8.0 hours. No tests required. Self-paced, mobile-friendly. Certificate downloadable immediately upon completion. No documentation submitted to DEA — physician simply checks attestation box on next DEA renewal. Free account required (email signup only). Board-certified addiction medicine/psychiatry physicians deemed auto-compliant per MATE Act. RxCE has 20+ years providing online CE. Founded to provide high-quality CE at low cost. Page confirmed active April 2026. No explicit expiration date listed (enduring activity).",
        url: "https://rxce.com/LandingPages/Mate",
        accreditation: "ACCME / ACPE / ANCC (Jointly Accredited Provider of IPE)",
        deaMateCompliant: true,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-24",
      },
      {
        name: "Pain Management and Opioids: Balancing Risks and Benefits",
        provider: "American Society of Addiction Medicine (ASAM) eLearning",
        providerUrl: "https://elearning.asam.org",
        credits: "2.5 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Recorded webinar (2018); covers prescribing habits, ER/LA medication differences, and patient safety principles for opioid management. Free for members and non-members alike. Register at elearning.asam.org → Free Sessions. ASAM holds ACCME Accreditation with Commendation.",
        url: "https://elearning.asam.org/ (navigate to Free Sessions)",
        accreditation: "ACCME (ASAM — Accreditation with Commendation)",
        deaMateCompliant: true,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-18",
      },
      {
        name: "OUD Decoded: A DEA-Compliant Audio Course",
        provider: "Hippo Education",
        providerUrl: "https://home.hippoed.com",
        credits: "12.25 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "$30",
        isFree: false,
        isHippo: true,
        description: "Audio (podcast-style) format for DEA MATE Act compliance. 12.25 AMA PRA Cat 1 credits — exceeds the 8-hour minimum. Covers OUD management, practice-changing guidance. Accessible format for busy EM physicians. Pricing not visible without login — confirm before listing as under $30.",
        url: "https://home.hippoed.com/oud-decoded",
        accreditation: "ACCME",
        deaMateCompliant: true,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-17 (URL confirmed active; price TBD)",
      }
    ],
  },
  ETHICS: {
    topicLabel: "Medical Ethics",
    requirement: "1-2 hours, recurring",
    courses: [
    // Auto-synced from Scout catalog — 2026-04-25T01:44:40.677Z
      {
        name: "ACP Ethics Manual, 7th Edition (CME Quiz Module)",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "10 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "25-question quiz based on the 7th edition of the ACP Ethics Manual — the foundational document of ACP ethics policy. Covers: patient-physician relationship, end-of-life care, informed consent, confidentiality, conflicts of interest, resource stewardship, research ethics, and more. Rereleased January 2025 with updated content; additional credit available for those who completed earlier versions. Expires January 13, 2028. Earns ABIM MOC points. This is one of the highest-credit free ethics activities available — 10 AMA PRA Cat 1 credits from a single enduring activity. ACP membership highly likely required to claim credit.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/acp-ethics-manual-7th-edition",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-18",
      },
      {
        name: "Ethical Dilemmas in Patient Care",
        provider: "Medscape Education",
        providerUrl: "https://www.medscape.org",
        credits: "1 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Explores common ethical challenges in clinical practice. Requires free Medscape account.",
        url: "https://www.medscape.org/public/ethics",
        accreditation: "ACCME",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-15",
      },
      {
        name: "ACP Ethics Case Study: Ethics, Professionalism, Physician Employment and Health Care Business Practices",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "1 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Case study exploring physicians' ethical obligation to prioritize patient welfare over self-interest in the context of employment terms, contracts, and business practices. Covers beneficence, non-maleficence, patient autonomy, and justice as applied to healthcare business decisions. Authors: Matthew DeCamp, MD, PhD; Lois Snyder Sulmasy, JD. Released June 2023. **⚠️ Expires June 12, 2026 — enroll soon.** Earns ABIM MOC points. Part of the ACP Ethics and Professionalism case study series.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/ethics-professionalism-physician-employment-and-health-care-business-practices",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-18",
      },
      {
        name: "Medical Ethics: Patient Autonomy and Confidentiality",
        provider: "Pri-Med",
        providerUrl: "https://www.pri-med.com",
        credits: "1 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Focuses on foundational principles of medical ethics in a primary care context.",
        url: "https://www.pri-med.com/online-education/ethics-cme",
        accreditation: "ACCME",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-15",
      },
      {
        name: "Boundaries for Physicians",
        provider: "AMA Ed Hub",
        providerUrl: "https://edhub.ama-assn.org",
        credits: "1 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free for AMA Members (varies for non-members)",
        isFree: true,
        isHippo: false,
        description: "Part of the AMA Code of Medical Ethics collection.",
        url: "https://edhub.ama-assn.org/pages/ethics-collection",
        accreditation: "ACCME",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-15",
      },
      {
        name: "ACP Ethics Case Study: \"Why Can't I Be There?\" Ethics Regarding Restrictions on Visitation/Family Caregiver Presence",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "0.75 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Ethics case study examining the tension between infection control visitor restrictions and patient/family-centered care obligations. Covers: ethical duties to patients and families, balancing public health vs. individual care, post-COVID visitor policy evolution. Authors: Kari Esbensen, MD, PhD, FACP; Amy Holbrook, MD, FACP; Lois Snyder Sulmasy, JD. Released April 2024. Expires April 18, 2027. Earns ABIM MOC points. Part of ACP Ethics and Professionalism case study series.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/why-cant-i-be-there-ethics-regarding-restrictions-on-visitationfamily-caregiver-presence",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-18",
      },
      {
        name: "ACP Ethics Case Study: Responding to Medical Misinformation and Disinformation and Protecting Scientific Discourse and Integrity",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "0.75 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Highly relevant ethics case study on physician responsibilities around medical misinformation. Covers: communicating scientific uncertainty, building patient trust, responding to disinformation, protecting scientific discourse and professional integrity. Authors: Erik A. Wallace, MD, MACP; Elliott J. Crigger, PhD; Jan K. Carney, MD, MPH, MACP; Lois Snyder Sulmasy, JD. Released April 2025. Expires April 23, 2028. Earns ABIM MOC points. Part of ACP Ethics and Professionalism case study series.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/responding-to-medical-misinformation-and-disinformation-and-protecting-scientific-discourse-and",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-18",
      },
      {
        name: "ACP Ethics Case Study: Raising Money from Patients? What's a Physician to Do?",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "0.5 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "ACP Ethics and Professionalism case study examining the ethical implications when physicians solicit charitable donations from patients — including conflicts with the patient-physician relationship, confidentiality concerns, community-institution relationships, and physician leadership. Authors: Elliott J. Crigger, PhD; Noel N. Deep, MD, MACP; Lois Snyder Sulmasy, JD. Released May 29, 2025. Expires May 28, 2028. Read the article then complete a brief survey and 100%-passing quiz to claim credit. Earns ABIM MOC points. ACP membership likely required for credit claiming.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/raising-money-from-patients-whats-a-physician-to-do",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-23 (URL confirmed live; credit, cost, and expiry all explicit on page)",
      },
      {
        name: "ACP Ethics Case Studies: Pain Management Near the End-of-Life: What Would Mom Want?",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "0.5 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "ACP Ethics and Professionalism case study series. Read article, then complete brief survey + multiple-choice quiz (100% passing, unlimited attempts). Covers end-of-life care ethics: symptom management, shared decision-making, palliative care obligations. Authors: Drs. Eduardo Bruera, Kari Esbensen, and Lois Snyder Sulmasy, JD. Released January 2024. Expires January 28, 2027. Earns ABIM MOC points. Pair with other ACP ethics case studies to accumulate more ethics credits (each case = 0.25–0.5 hr). Part of a series of 15+ free ACP ethics case studies at acponline.org/clinical-information/medical-ethics-and-professionalism/ethics-case-studies-education-resources",
        url: "https://www.acponline.org/cme-moc/online-learning-center/pain-management-near-the-end-of-life-what-would-mom-want",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-18",
      },
      {
        name: "ACP Ethics Case Study: Updating the Information Blocking Rule: Implications for Patients and Physicians",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "0.25 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "ACP Ethics and Professionalism journal-article case study on recent regulatory changes to the federal information-blocking rule and what delayed release of certain results means for physicians and patients. Read the case study, review supplemental material, then complete the CME/MOC survey. Released April 3, 2026. Expires April 2, 2029. Earns ABIM MOC points. ACP membership required to claim credit.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/updating-the-information-blocking-rule-implications-for-patients-and-physicians",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-24 (OLC page explicitly states 0.25 AMA PRA Category 1, Free to Members, ACCME accreditation, and Apr 2029 expiry)",
      },
      {
        name: "ACP Ethics Case Study Series (Platform Note — 15+ Free Cases)",
        provider: "American College of Physicians (ACP) — Center for Ethics and Professionalism",
        providerUrl: "https://www.acponline.org",
        credits: "0.25 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "ACP maintains a library of 15+ ethics case studies, each earning AMA PRA Cat 1 CME/MOC credits. Topics include: end-of-life care, information blocking, SUD and medical records, misinformation, professional boundaries/chaperones, telemedicine ethics, physician social media, resource allocation, firearm safety, and more. Each case is read as a journal article then completed with a brief survey/quiz. Individually cataloged cases: Pain Management/End-of-Life (0.5hr), Chaperones/Boundaries (0.25hr), Raising Money from Patients (0.5hr). Highly recommended for stacking ethics credits from a single trusted ACCME-accredited source.",
        url: "https://www.acponline.org/clinical-information/medical-ethics-and-professionalism/ethics-case-studies-education-resources",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-23 (hub page reconfirmed; 11 new cases identified in hub; Raising Money from Patients newly cataloged)",
      },
      {
        name: "ACP Ethics Case Studies: Chaperones, Professional Boundaries and the Potential for Misunderstandings",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "0.25 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "ACP Ethics and Professionalism case study. Covers professional boundaries, chaperone use during intimate exams, patient-physician trust, and avoiding misunderstandings. Authors: Charlene Dewey, MD, MEd; Paula Katz; Lois Snyder Sulmasy, JD. Released September 2024. Expires September 11, 2027. Earns ABIM MOC points. Part of the same ACP ethics case study series (15+ cases available). See acponline.org/clinical-information/medical-ethics-and-professionalism/ethics-case-studies-education-resources for full list.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/chaperones-professional-boundaries-and-the-potential-for-misunderstandings",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-18",
      }
    ],
  },
  IMPLICIT_BIAS: {
    topicLabel: "Implicit Bias / Cultural Competency",
    requirement: "1-2 hours, recurring",
    courses: [
    // Auto-synced from Scout catalog — 2026-04-25T01:44:40.677Z
      {
        name: "The Explicit Need for Implicit Bias and Cultural Competence Training in the Health Professions",
        provider: "ScientiaCME",
        providerUrl: "https://www.scientiacme.org",
        credits: "1.5 AMA PRA Category 1 + ABIM MOC Points + ABP MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Comprehensive coverage of cultural competence, implicit bias, and health equity. Topics include: principles of cultural competence, implicit bias in healthcare decision-making, LGBTQIA+ considerations, populations with limited English proficiency, underserved communities (aged, race/ethnicity, SES), CLAS standards, patient-centered communication strategies. Earns ABIM and ABP MOC points. Target audience: physicians, pharmacists, PAs, NPs, and other HCPs. Expires July 4, 2026 — active now. **NJ physicians:** pair with Advocate Health implicit bias course (both free) for full 2hr NJ compliance.",
        url: "https://www.scientiacme.org/cme-528-111-0-1-10-bias-cultural-competence-training-cme",
        accreditation: "ACCME (Activity #202796178)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; meets CA (no fixed hour min for implicit bias), IL (requires implicit bias CME), MD (requires implicit bias CME), NY (1hr required — covered by this course alone). **NJ note:** NJ (P.L.2021 c.96) requires 2hr/cycle — combine with Advocate Health implicit bias course (1.0hr, free, above) for 2.5hr total to satisfy NJ's 2hr requirement.",
        verified: "2026-04-18",
      },
      {
        name: "Implicit Bias Awareness Training for Licensed Healthcare Professionals 2026",
        provider: "Advocate Health (Advocate Aurora Health — jointly accredited)",
        providerUrl: "https://ce.advocatehealth.org",
        credits: "1 AMA PRA Category 1 (+ ANCC 1.0 contact hour + ACPE 1.0 CPE + ASWB 1.0 cultural competence CE)",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "2026 edition enduring activity covering implicit bias awareness for licensed healthcare professionals. Jointly accredited — earns credit for physicians, nurses, pharmacists, social workers, PT/OT/SLP. ABS board continuous certification credit available. Developed by Advocate Health (one of the largest U.S. health systems — Advocate Aurora + Atrium Health). No registration fee shown — appears to be free for all HCPs. **IL-specific IDFPR approval confirmed.** Pair with ScientiaCME course (1.5hr, free) for full NJ 2hr compliance.",
        url: "https://ce.advocatehealth.org/content/advocate-health-implicit-bias-awareness-training-licensed-healthcare-professionals-2026",
        accreditation: "ACCME / ACPE / ANCC (jointly accredited); Wisconsin Medical Society–accredited for physician CME",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1. **IL:** Explicitly approved by Illinois IDFPR (IL PT/OT/SLP license 216.000106); meets IL implicit bias requirement. **NJ:** Combine with ScientiaCME (1.5hr) for 2.5hr total to satisfy NJ's 2hr requirement (P.L.2021 c.96). Meets CA, MD, NJ, NY implicit bias requirements.",
        verified: "2026-04-19",
      },
      {
        name: "Implicit Bias in Medicine and Healthcare: Science and Solutions",
        provider: "MedStar Health",
        providerUrl: "https://medstar.cloud-cme.com",
        credits: "1 AMA PRA Category 1 (+ ANCC 1.0 + ACPE 1.0 + AAPA + ASWB Social Worker Cultural Competence + IPCE)",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Evidence-based interprofessional CME on implicit bias — definition, how it affects behavior and patient care, strategies to mitigate bias in clinical context. Covers physician decision-making, interpersonal interactions, and clinical care quality. Active July 20, 2023 – July 19, 2026. All medical specialties listed (incl. Emergency Medicine). Physicians and all HCP types eligible. Free access via MedStar Health CME portal. Social Worker Cultural Competence credit available. Interprofessional CME (IPCE) credit.",
        url: "https://medstar.cloud-cme.com/course/courseoverview?P=5&EID=27090",
        accreditation: "ACCME / ACPE / ANCC (jointly accredited by MedStar Health)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; meets IL, CA, MD, NJ (pair with other implicit bias course for NJ 2hr total), NY implicit bias requirements",
        verified: "2026-04-21",
      },
      {
        name: "Unconscious Bias in Medicine",
        provider: "Stanford University School of Medicine (via Stanford Online / edX)",
        providerUrl: "https://online.stanford.edu",
        credits: "1 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "100% online, on-demand via edX. Self-paced. \"The Stanford University School of Medicine designates this enduring material for a maximum of 1.0 AMA PRA Category 1 Credits™.\" Covers unconscious bias effects in healthcare settings, bias-busting techniques, self-assessment tools, strategies for bias correction in daily interactions. **Note:** This course is on Stanford Online (online.stanford.edu via edX) — separate from the dead cme.stanford.edu platform. CME credit awarded by Stanford Center for CME. Credit claiming may require edX enrollment. Interprofessional — physicians, nurses, PAs, and all HCPs eligible.",
        url: "https://online.stanford.edu/courses/som-ycme0027-unconscious-bias-medicine",
        accreditation: "ACCME (Stanford Center for Continuing Medical Education)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; meets IL, CA, MD, NJ (pair with another course for NJ 2hr), NY implicit bias requirements",
        verified: "2026-04-21 (via MOOC-list and opencourser.com confirming AMA PRA Cat 1 designation; $0.00 confirmed on Stanford Online course page)",
      },
      {
        name: "~~Unveiling Unconscious Bias~~ ⚠️ LINK BROKEN — DO NOT USE",
        provider: "Stanford Center for CME",
        providerUrl: "",
        credits: "0",
        creditType: "AMA_PRA_1",
        price: "Unknown",
        isFree: true,
        isHippo: false,
        description: "~~Unveiling Unconscious Bias~~ ⚠️ LINK BROKEN — DO NOT USE",
        url: "",
        accreditation: "",
        deaMateCompliant: false,
        stateAcceptance: "",
        verified: "",
      }
    ],
  },
  PATIENT_SAFETY: {
    topicLabel: "Patient Safety / Medical Error Prevention",
    requirement: "2 hours, recurring (FL, MA, CT)",
    courses: [
    // Auto-synced from Scout catalog — 2026-04-25T01:44:40.677Z
      {
        name: "High-Value Care Cases",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "5 AMA PRA Category 1 + ABIM MOC Points (13 MOC points)",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "ACP's High Value Care initiative — case-based learning covering benefits, harms, and costs of common diagnostic tests and treatment options. Interactive audio/video format. Mobile-friendly. Earns 5 AMA PRA Cat 1 credits and 13 ABIM MOC points. Free to all — no ACP membership required. Accessed at ACP Online Learning Center. High-value care principles directly support patient safety competencies required in many states.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/high-value-care-cases",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; meets FL and PA patient safety requirements",
        verified: "2026-04-18",
      },
      {
        name: "Prevention of Medical Errors 2024-2026 (National)",
        provider: "The Doctors Company (medical liability insurer)",
        providerUrl: "https://thedoctors.cloud-cme.com",
        credits: "2 AMA PRA Category 1 / ANCC Nursing Contact Hours (2.0 hr)",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Enduring online CME. Target audience explicitly includes Emergency Medicine, Family Medicine, Internal Medicine, Cardiology, Surgery, Pediatrics, OB/GYN, and many more specialties. Covers common performance and diagnostic errors, root cause analysis, culture of safety, and patient communication strategies. Score 80%+ on post-test to earn credit. Active July 1, 2024 – July 1, 2026. The Doctors Company is ACCME-accredited. Available to any physician regardless of insurer. No account required beyond registration on the CME portal.",
        url: "https://thedoctors.cloud-cme.com/course/courseoverview?P=0&EID=3749",
        accreditation: "ACCME (The Doctors Company) + ANCC (nursing)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; specifically covers Florida patient safety requirements",
        verified: "2026-04-20",
      },
      {
        name: "2026 Prevention of Medical Errors: To Err is Human",
        provider: "AdventHealth Orlando CME",
        providerUrl: "https://adventhealth.cloud-cme.com",
        credits: "2 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Online enduring material. Covers medical errors scope in the US, why errors happen, root cause analysis, and patient safety improvement strategies. Original release Nov 2023; reviewed March 4, 2026; expires December 31, 2026. All specialties included. CE Broker integration: enter FL license number in profile to auto-upload FL CME credit. FMA accreditation is ACCME-recognized — accepted nationally. Faculty: AdventHealth CPD Department.",
        url: "https://adventhealth.cloud-cme.com/default.aspx?P=0&EID=24076",
        accreditation: "Florida Medical Association (FMA) — ACCME-recognized state medical society",
        deaMateCompliant: false,
        stateAcceptance: "Florida — explicitly FL Board of Medicine approved; CE Broker upload available (enter FL license number in profile). All states accepting AMA PRA Category 1.",
        verified: "2026-04-20",
      },
      {
        name: "Medical Errors: Identifying and Avoiding Common Misdiagnoses in Clinical Practice (Parts 1 & 2)",
        provider: "Pri-Med Institute",
        providerUrl: "https://www.pri-med.com",
        credits: "1 AMA PRA Category 1 / CE",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Two-part series on medical errors and misdiagnosis. Part 1 covers GI and oncology misdiagnoses. Part 2 covers cardiology, infectious disease, and neurology misdiagnoses plus adverse event disclosure. Faculty: Panagiota Caralis, MD, JD, FACP (Univ. of Miami / Miami VA Hospital). Specifically designed to satisfy state CME requirements for Medical Errors/Patient Safety/Risk Management. Each part = 1.0 hr AMA PRA Cat 1. Free account required at pri-med.com. Pri-Med Institute is ACCME-accredited. Note: Texas approves this for Medical Ethics (not Patient Safety) credit — check your state board for category alignment.",
        url: "https://www.pri-med.com/online-cme-ce/webcast/medical-errors-identifying-and-avoiding-common-misdiagnoses-in-clinical-practice-part-1 (Part 1); https://www.pri-med.com/online-cme-ce/webcast/medical-errors-identifying-and-avoiding-common-misdiagnoses-in-clinical-practice-part-2 (Part 2)",
        accreditation: "ACCME (Pri-Med Institute)",
        deaMateCompliant: false,
        stateAcceptance: "Florida — CE Broker Provider #50-27480, Activity #20-1081562 (FL Board of Medicine approved). Texas — approved for Medical Ethics credit (MD/DO). All states accepting AMA PRA Category 1.",
        verified: "2026-04-20",
      }
    ],
  },
  SUICIDE_PREVENTION: {
    topicLabel: "Suicide Prevention & Awareness",
    requirement: "2 hours (initial, then every 4 years)",
    courses: [
    // Auto-synced from Scout catalog — 2026-04-25T01:44:40.677Z
      {
        name: "Mental Health as a Vital Sign: Addressing Health Professionals' Suicide Risk and Enhancing Mental Health",
        provider: "AAFP (American Academy of Family Physicians)",
        providerUrl: "https://www.aafp.org",
        credits: "1.75 AMA PRA Category 1 / AOA Category 2 equivalent / AAFP Prescribed",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Free online CME focused on suicide risk reduction in health professionals (physician wellbeing focus, not primarily patient-facing). Faculty: Christine Yu Moutier, MD (AFSP Chief Medical Officer). Covers organizational strategies to reduce suicide risk among healthcare workers. AAFP Prescribed credits count toward Nevada's suicide prevention requirement. Approved through April 1, 2029. Note: This course is physician-focused rather than patient-focused — pairs well with a patient-focused suicide prevention course to meet full hour requirements. Term of Approval: 04/01/2026–04/01/2029.",
        url: "https://www.aafp.org/cme/all/physician-well-being/mental-health-as-a-vital-sign.html",
        accreditation: "ACCME (AAFP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; meets Nevada suicide prevention requirement (partial — 1.75 of 2 hrs required every 4 years)",
        verified: "2026-04-18",
      },
      {
        name: "Project ECHO Addiction/SUD/Behavioral Health Programs (CME Available via iECHO)",
        provider: "Project ECHO (University of New Mexico)",
        providerUrl: "https://iecho.org",
        credits: "1 AMA PRA Category 1 / ANCC",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "ECHO teleECHO sessions offer CME for live attendance. Topics include addiction, SUD, mental health, and suicide prevention. Register at iecho.org to find a program near your specialty. Many sessions are weekly and free to join. CME credit typically requires live attendance.",
        url: "https://iecho.org/welcome (register and search addiction/behavioral health programs)",
        accreditation: "ACCME (varies by hub — check individual program)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-16",
      },
      {
        name: "Identifying and Responding to Suicide Risk",
        provider: "American Medical Association (AMA Ed Hub)",
        providerUrl: "https://edhub.ama-assn.org",
        credits: "1 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Online enduring module. Covers suicide prevalence/impact, identifying at-risk patients, recognizing warning signs in colleagues, tools/resources to support at-risk individuals, communication techniques for suicide prevention. ABMS Lifelong Learning CME approved by 15 specialty boards including Family Medicine, Preventive Medicine, and Psychiatry. AMA members: free. Non-members: $20. Expires May 13, 2028. Pairs with AAFP mental health course to potentially cover Nevada's 2-hour suicide prevention requirement. Direct URL blocked by Cloudflare — access through edhub.ama-assn.org with AMA login.",
        url: "https://edhub.ama-assn.org/ (Activity ID: 3841 — search \"suicide risk\" on AMA Ed Hub)",
        accreditation: "ACCME (AMA)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; meets Nevada suicide prevention requirement (partial — 1 of 2 hrs required every 4 years); multiple ABMS board approvals",
        verified: "2026-04-18 (confirmed via ABMS continuingcertification.org listing)",
      },
      {
        name: "Physician Suicide Prevention: The Ethics and Role of the Physician Colleague and the Healing Community",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "0.5 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Ethics case study format. Read article, then complete brief survey + multiple-choice quiz (100% passing score required, unlimited attempts). Rereleased October 15, 2024. Expires October 14, 2027. Covers suicide awareness, stressors in medicine, guidance for colleagues at risk. ACP members: free. Dual credit: Ethics + Suicide Prevention (counts for both topics in states like Nevada). ABIM MOC points included.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/physician-suicide-prevention-the-ethics-and-role-of-the-physician-colleague-and-the-healing",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-18",
      }
    ],
  },
  DOMESTIC_VIOLENCE: {
    topicLabel: "Domestic Violence",
    requirement: "1-2 hours (varies by state)",
    courses: [
    // Auto-synced from Scout catalog — 2026-04-25T01:44:40.677Z
      {
        name: "ENDURING: Domestic Violence Prevention (2026)",
        provider: "Memorial Healthcare System CME (South Florida)",
        providerUrl: "https://mhs.cloud-cme.com",
        credits: "2 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Enduring material. Post-test required (70% passing score, up to 5 attempts). Topics: DV statistics, risk groups, incidence/prevalence, screening/assessment techniques, community resources. Active 2026 edition confirmed live. Faculty: Randy Katz, DO.",
        url: "https://mhs.cloud-cme.com/default.aspx?P=0&EID=22591",
        accreditation: "ACCME (Memorial Healthcare System)",
        deaMateCompliant: false,
        stateAcceptance: "Florida — directly satisfies FL Board of Medicine mandatory 2-credit DV requirement (every third biennium). Accepted by all states accepting AMA PRA Category 1.",
        verified: "2026-04-16",
      },
      {
        name: "Update on Domestic Violence (2025)",
        provider: "Baptist Health South Florida CME",
        providerUrl: "https://cmeonline.baptisthealth.net",
        credits: "2 AMA PRA Category 1 (MOC also available: ABS, ABOS)",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Enduring material. Satisfies Florida relicensure DV requirement for physicians, podiatrists, dentists, PAs, nurses, and social workers. Post-test required for certificate. Faculty: Nancy Eklund, MD (Family Physician, Baptist Health).",
        url: "https://cmeonline.baptisthealth.net/domestic-violence-2025",
        accreditation: "ACCME (Baptist Health South Florida — ACCME Commendation, 6-year designation)",
        deaMateCompliant: false,
        stateAcceptance: "Florida — CE Broker Course #20-1110184, approved by FL Board of Medicine, Podiatry, Dentistry, FL Council of PAs, FL Board of Nursing, FL Board of Clinical Social Work/MFT/MHC. CE Broker Provider #50-182.",
        verified: "2026-04-16",
      },
      {
        name: "Intimate Partner Violence: Educating and Connecting (Part 2 of 2)",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "1.75 AMA PRA Category 1 + MOC Points (ABIM)",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Part 2 of a 2-part series on IPV. Interactive multi-media format with audio version available. Covers universal education approaches, prevention strategies, and health/safety outcomes for IPV patients. Expires October 13, 2028. Authors: Elizabeth Miller, MD, PhD (Univ. of Pittsburgh) and Lisa James (Futures Without Violence). Non-members can purchase access per module at $25. Part 1 may be available separately — check ACP Online Learning Center.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/intimate-partner-violence-educating-and-connecting",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-16",
      },
      {
        name: "Domestic Violence & Abuse CME (Multiple Courses)",
        provider: "Pri-Med",
        providerUrl: "https://www.pri-med.com",
        credits: "0 AMA PRA Category 1 / CE",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Pri-Med offers multiple free DV/abuse CME courses covering identification of abuse types (physical, emotional, financial, sexual), culturally sensitive screening, documentation, legal considerations, and referral strategies. Free account required (no subscription fee). Target audience includes MDs, DOs, NPs, PAs. Specific course titles and hours vary — log in and search \"domestic violence\" for current offerings.",
        url: "https://www.pri-med.com/topic/domestic-violence-cme",
        accreditation: "ACCME",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-16",
      }
    ],
  },
  HUMAN_TRAFFICKING: {
    topicLabel: "Human Trafficking",
    requirement: "1 hour (TX, MI, DC)",
    courses: [
    // Auto-synced from Scout catalog — 2026-04-25T01:44:40.677Z
      {
        name: "Identifying Human Trafficking: What Physicians Need to Know",
        provider: "Texas Medical Association (TMA)",
        providerUrl: "https://www.texmed.org",
        credits: "1 AMA PRA Category 1 / Ethics Credit",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Fulfills both Ethics and Human Trafficking requirements for many states.",
        url: "https://www.texmed.org/Education/",
        accreditation: "ACCME",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1. Specifically meets Texas mandatory requirement.",
        verified: "2026-04-15",
      },
      {
        name: "Signs of Human Trafficking and Response: A Physician's Guide",
        provider: "American College of Physicians (ACP)",
        providerUrl: "https://www.acponline.org",
        credits: "1 AMA PRA Category 1 + ABIM MOC Points",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Interactive multi-media module (audio version available). Rereleased June 3, 2025 with updated content. Original release February 2019. Covers trafficking identification in clinical settings, trauma-informed response, and mandatory reporting. Pass 66% quiz to earn credit. Expires June 2, 2027. Authors: Davoren Chick MD FACP and Rebecca Andrews MS MD FACP. Free to all — no membership required.",
        url: "https://www.acponline.org/cme-moc/online-learning-center/human-trafficking-identification-and-response",
        accreditation: "ACCME (ACP)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; meets Virginia mandatory human trafficking CE requirement (VA Board of Medicine)",
        verified: "2026-04-17",
      },
      {
        name: "On-Demand Human Trafficking Grand Rounds CME (Multiple Courses)",
        provider: "Baylor College of Medicine (BCM) Clinician Resources",
        providerUrl: "https://clinicianresources.bcm.edu",
        credits: "1 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "⚠️ VERIFICATION NEEDED — BCM listing page shows 8 on-demand human trafficking courses labeled \"Credit,\" but individual course pages verified 2026-04-20 show some older courses (2023) are \"archived and credit is no longer available.\" One confirmed current active course: \"Human Trafficking, Sex Work, and the Risk of Substance Use Disorders\" (BCM Menninger Psychiatry Grand Rounds, May 7, 2025, 1hr, On Demand, Credit) — appearing in BCM's Texas CME requirements listing as active. BCM is ACCME-accredited and their CME is free (no payment system found). Direct URL for the May 2025 session not yet confirmed — access through the listing page and filter by date. Recommend verifying individual course \"Term of Approval\" before directing physicians to this resource.",
        url: "https://clinicianresources.bcm.edu/interest-group/human-trafficking/",
        accreditation: "ACCME (Baylor College of Medicine)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; meets Texas mandatory human trafficking training requirement",
        verified: "2026-04-20 (listing live; individual course status mixed — some archived, at least one 2025 session appears active)",
      },
      {
        name: "Human Trafficking: Identification and Response from Health Care Providers",
        provider: "HCA Healthcare Continental Division",
        providerUrl: "https://cme.healthonecares.com",
        credits: "1 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "Enduring online activity covering human trafficking identification and clinical response for healthcare providers. No commercial support. Developed without industry funding. HCA Healthcare Continental Division is ACCME-accredited. Page is publicly accessible on cme.healthonecares.com — no HCA employment required to access. Cost confirmed as no commercial support listed and public access URL. Verify registration is open (free account may be required).",
        url: "https://cme.healthonecares.com/content/human-trafficking-identification-and-response-health-care-providers-0",
        accreditation: "ACCME (HCA Healthcare Continental Division)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1",
        verified: "2026-04-21 (URL live, accreditation confirmed; registration cost not shown — likely free with account)",
      },
      {
        name: "Human Trafficking in a Clinical Setting: Your Role and Responsibility",
        provider: "AMA Ed Hub / Hope for Justice Education",
        providerUrl: "https://edhub.ama-assn.org",
        credits: "0.5 AMA PRA Category 1",
        creditType: "AMA_PRA_1",
        price: "Free",
        isFree: true,
        isHippo: false,
        description: "AMA Ed Hub course from Hope for Justice (anti-trafficking nonprofit). Endorsed on AMA.org physician resources page. Specifically recommended by Inova Health System CME for Virginia mandatory human trafficking training. AMA Ed Hub is Cloudflare-protected — direct URL confirmed from Inova CME page and AMA search. Free account required at edhub.ama-assn.org. Exact credit hours require login to confirm.",
        url: "https://edhub.ama-assn.org/hope-for-justice-edu/module/2808105",
        accreditation: "ACCME (AMA)",
        deaMateCompliant: false,
        stateAcceptance: "All states accepting AMA PRA Category 1; cited by Inova CME as meeting Virginia Board of Medicine human trafficking CE requirement",
        verified: "2026-04-17 (URL confirmed via Inova CME portal; direct access requires AMA Ed Hub login)",
      }
    ],
  },
};

/** Convert a URL-slug back to a COURSE_CATALOG key.
 *  e.g. "substance-use" → "SUBSTANCE_USE"
 */
export function slugToKey(slug: string): string {
  return slug.toUpperCase().replace(/-/g, "_");
}

/** Convert a COURSE_CATALOG key to a URL slug.
 *  e.g. "SUBSTANCE_USE" → "substance-use"
 */
export function keyToSlug(key: string): string {
  return key.toLowerCase().replace(/_/g, "-");
}
