export type NationalGuide = { slug: string; title: string; description: string; sections: { title: string; paragraphs: string[] }[]; faqs: { question: string; answer: string }[]; relatedStates: string[] };
export const nationalGuides: NationalGuide[] = [
  {
    slug: "multi-state-cme-requirements", title: "How to manage CME requirements across multiple states",
    description: "Build a multi-state physician CME plan around each board’s cycle, category rules, mandatory topics and official reporting requirements.",
    sections: [
      { title: "Start with one row per license", paragraphs: ["Record the state, MD or DO license, actual renewal date, reporting-period start and end, total hours, category floors and official reporting destination. Take the dates from the board record. A two-year renewal does not mean every topic uses a two-year clock.", "Keep federal DEA training in a separate row. It belongs in the same planning system, but it is not another state’s annual-hour requirement."] },
      { title: "Separate the total from the constraints", paragraphs: ["Create a checklist for each mandatory topic: applicable practice conditions, required hours, accepted provider, due date, recurring interval and evidence of prior completion. Flag unanswered questions before booking more CME.", "For example, a California DO needs to check the AOA category floor; a New York physician needs to track specific training even though there is no general hour minimum. The linked state guides explain these distinctions and their sources."] },
      { title: "Find courses that work across licenses", paragraphs: ["A single activity may be useful for more than one license. Test it against each board independently: completion window, category, topic content and any approved-provider restriction. A course title containing “opioid” does not prove acceptance for every opioid requirement.", "Count the actual hours earned. If an activity satisfies multiple categories, record which requirements it meets while keeping the hours equal to the time earned. Ask the board or provider when acceptance is unclear."] },
      { title: "Work backward from the earliest deadline", paragraphs: ["Sort requirements by their own due dates, including one-time and first-licensure deadlines. Prioritize mandatory courses that have few approved options, then complete remaining general hours. Preserve a buffer for provider reporting or certificate corrections.", "Before each renewal, reconcile the official reporting system with your records. A complete tracker is useful preparation; it is not the board’s renewal submission."] },
      { title: "A practical record to keep", paragraphs: ["For every course, save the certificate, activity date, earned hours, exact accreditation wording, provider, topic evidence and the licenses for which you checked acceptance. Keep a list of courses that still need confirmation from a board or provider.", "ClearCME can organize licenses, certificates and recorded completion history. Review its stated limitations, especially Nevada’s DO transition and reduced first-cycle MD requirements, before relying on a displayed status."] },
    ],
    faqs: [
      { question: "Can the same CME count in two states?", answer: "Potentially, if it independently meets each state’s rules and falls within both applicable periods. Confirm that the activity meets the specific requirement for each license." },
      { question: "Should I add all state hour totals together?", answer: "Use each state’s total as its own target. Adding the totals can overstate the new training you need when activities qualify in more than one jurisdiction." },
      { question: "What should I do if the tracker and board disagree?", answer: "Use the board’s current rule and your official record. Save the source and report the discrepancy so the product and educational guidance can be corrected together." },
    ], relatedStates: ["california", "nevada", "new-york"],
  },
  {
    slug: "how-to-track-cme-credits", title: "How to track physician CME hours and certificates",
    description: "A practical system for tracking CME hours, certificates, categories, topic deadlines and official reporting across physician licenses.",
    sections: [
      { title: "Create a record that can be checked", paragraphs: ["For each activity, record its exact title, provider, completion date, hours actually earned and accreditation category. Attach the original certificate. Keep the activity URL and any state-approval evidence with that record.", "Avoid using the activity’s advertised maximum as your earned total. The certificate and your actual participation are the evidence for the hours you claim."] },
      { title: "Assign the right renewal period", paragraphs: ["Record the start and end of each board’s reporting window. Keep renewal date, reporting window and mandatory-topic deadline in separate fields; they are not interchangeable.", "Before reusing older training, check whether you are documenting a lifetime requirement, using an allowed carryover provision or claiming hours in the current cycle. Those are different uses of the same record."] },
      { title: "Track topics and categories separately", paragraphs: ["A course can have the right topic but the wrong accepted accreditation for a particular license. Record the exact category rather than a generic “CME” label. If only part of a course covers a mandatory topic, save the syllabus or provider documentation supporting the allocation.", "Mark a course for review if you still need to confirm its category, topic coverage or board acceptance. Resolve those questions before counting it toward your renewal."] },
      { title: "Reconcile after each activity", paragraphs: ["Download the certificate while the provider account and activity are easy to find. Check the name, date and earned hours, then compare the record with any official reporting platform used by the board.", "Before renewal, review missing topics, one-time completions, expiring intervals and course approvals. Keep the official submission confirmation after renewal."] },
      { title: "Use software where it saves work", paragraphs: ["ClearCME lets you organize licenses and upload certificates. Review extracted fields against the original before relying on them. Duplicate certificates, unclear categories or topic allocations can require your confirmation.", "Keep access to the original evidence outside any single summary screen. Board reporting, exemptions and individual acceptance decisions remain separate responsibilities."] },
    ],
    faqs: [
      { question: "Is a spreadsheet enough?", answer: "It can be, if it preserves the correct dates, categories, topic rules and supporting documents. Software primarily reduces repeated entry and helps keep those records connected." },
      { question: "Should I keep certificates after renewal?", answer: "Yes. Follow your board’s retention requirement and preserve one-time training evidence beyond the current cycle. Different boards can specify different periods." },
      { question: "Should I trust automatically extracted hours?", answer: "Compare them with the certificate, particularly when an activity advertises a maximum or contains multiple category labels. Correct errors before using the record for renewal." },
    ], relatedStates: ["california", "texas", "florida"],
  },
  {
    slug: "cme-audit-checklist", title: "A physician’s CME audit checklist",
    description: "Prepare an inspectable CME record: certificates, dates, categories, mandatory-topic proof, exemptions and official reporting confirmations.",
    sections: [
      { title: "Read the audit notice first", paragraphs: ["Identify the requesting board, license type, reporting period, response deadline and accepted submission method. Preserve the notice. Work from the requested period rather than your current dashboard total.", "Use the submission format and record-retention rules specified by the board requesting the audit."] },
      { title: "Gather the evidence", paragraphs: ["Collect original certificates with course titles, dates, earned hours, sponsors and accepted accreditation. Add a compact index so each claimed activity can be matched to its document.", "Include mandatory-topic evidence, such as the curriculum or approved-provider listing, when needed to show why a course qualifies. A general certificate may not explain how many hours addressed a particular topic."] },
      { title: "Check exceptions and prior completions", paragraphs: ["Keep documentation for board-approved exemptions, residency/fellowship pathways and other alternatives you relied on. Save the approval or other evidence showing that the exemption applies to you.", "For one-time requirements, retrieve the original completion evidence even if the activity predates the audited cycle. Keep a clear explanation of why an older document is included."] },
      { title: "Reconcile the totals", paragraphs: ["Check dates, category floors and topic-specific hours separately. Remove duplicate certificates and avoid treating maximum available hours as hours earned. Compare your index with any official CE record.", "If evidence is missing, request a replacement from the provider. Explain unresolved discrepancies accurately rather than altering a certificate or declaring unsupported hours."] },
      { title: "Submit through the official channel", paragraphs: ["Follow the board’s instructions for files, forms and delivery. Save the final packet and submission confirmation. A ClearCME export can help organize supporting records where your plan includes it; it does not itself complete the board’s audit response.", "Afterward, update your routine so future certificates, approvals and confirmations are saved as they arrive. The next renewal should not require reconstructing the same history."] },
    ],
    faqs: [
      { question: "Does this checklist replace my board’s audit instructions?", answer: "No. It helps organize the response. Your board’s notice controls the period, required evidence, format and deadline." },
      { question: "Is a total-hour screenshot enough?", answer: "Use the evidence required by the board. An aggregate total usually does not identify the underlying activity, category, date and topic support; keep the certificates available." },
      { question: "What if I lost a certificate?", answer: "Ask the original provider for a replacement or accepted completion record. Keep that correspondence and be clear about any evidence still missing." },
    ], relatedStates: ["california", "florida", "nevada"],
  },
  {
    slug: "cme-requirements-vs-license-renewal", title: "CME requirements vs. medical license renewal",
    description: "Understand the difference between completing CME, meeting a topic deadline, reporting education and renewing a physician license.",
    sections: [
      { title: "Four steps that are easy to confuse", paragraphs: ["Completing training, keeping proof, reporting CME and renewing a license are connected but separate steps. Finishing a course does not automatically submit a renewal application. Uploading a certificate to a tracker does not automatically report it to a board.", "Write down who receives each submission: course provider, board-designated CE system, medical board or DEA. Keep a confirmation for each completed official step."] },
      { title: "The renewal clock is not the only clock", paragraphs: ["A board can require a two-year registration while particular topics recur on another interval. New York’s physician registration and specific training intervals illustrate why one calendar reminder is insufficient.", "First-licensure deadlines and one-time training can also fall before an ordinary renewal. Use the actual issue date and completion history when a rule depends on them."] },
      { title: "CME is only one part of renewal", paragraphs: ["The board may also ask for an application, fees, profile updates, attestations or other profession-specific information. Use its current renewal checklist for your exact license type and status.", "Florida’s MD renewal page, for example, lists CME alongside other administrative requirements. Completing the hour target should not be treated as proof that the entire renewal is finished."] },
      { title: "Official reporting stays official", paragraphs: ["Texas and Florida use CE Broker in their official reporting workflows. Follow the current board instructions, check the reported record and resolve discrepancies before renewal.", "ClearCME organizes records and shows information based on the data entered and supported product rules. It does not renew a license, file a DEA attestation or guarantee a board will accept a particular course."] },
      { title: "Make a two-part renewal checklist", paragraphs: ["First, check education: applicable total, category floors, mandatory topics, completion windows, exceptions and evidence. Second, check administration: official reporting, application, requested documents, payment and confirmation.", "Save the renewed license record and update the next expiration date only after the official process is complete. Keep one-time training records accessible for later cycles."] },
    ],
    faqs: [
      { question: "If all my CME is complete, is my license renewed?", answer: "No. You still need to complete the board’s renewal process and confirm the renewed status in the official record." },
      { question: "Does a tracker replace CE Broker?", answer: "No. When your board requires official reporting in CE Broker, you must complete that reporting. A personal tracking tool is a separate organizational aid." },
      { question: "Which deadline should I put on my calendar?", answer: "Record the license expiration and every independently timed topic or initial-training deadline. Set separate reminders for requirements with different deadlines." },
    ], relatedStates: ["new-york", "texas", "florida"],
  },
  {
    slug: "free-cme-for-mandatory-requirements", title: "How to find free CME for mandatory requirements",
    description: "Find free physician CME without assuming every topic match qualifies: check board approval, accreditation, current price and certificate details.",
    sections: [
      { title: "Start with the exact requirement", paragraphs: ["Write down the required topic, hours, accepted category, completion window and any approved-provider restriction before searching for a course. A free activity is useful only if it meets the requirement you actually owe.", "Check the board’s approved-course list first when one exists. Texas human-trafficking training and New York mandated training have approval conditions that a generic topic search can miss."] },
      { title: "Check whether free really means free", paragraphs: ["Open the specific activity page and confirm the current price, account requirements and whether the certificate is included. Membership-only access is different from free access available to every physician.", "Check that the activity is still open for the relevant accreditation and that you can finish before its expiration. A saved recommendation can become stale even when the web page still loads."] },
      { title: "Read the accreditation statement", paragraphs: ["Compare the actual category and hours with your license’s requirements. AMA Category 1 and AOA Category 1-A may meet different board requirements and category minimums.", "If the activity promises state acceptance, look for the specific state, profession and requirement. Save the approval statement or approved-list entry alongside the certificate."] },
      { title: "Avoid paying for a topic you already completed", paragraphs: ["Check your history before purchasing a one-time course. DEA permits qualifying earlier training and several eligibility pathways for MATE Act compliance. Read the federal guide before assuming you must buy a fresh eight-hour bundle.", "For recurring state topics, verify the required interval and whether your prior course falls within it. One-time federal training does not automatically satisfy a recurring state course."] },
      { title: "Use the library as a shortlist", paragraphs: ["Browse ClearCME’s topic pages to compare provider information, then verify the current activity and your board’s rules. The library is a discovery aid; a topic link alone is not an acceptance guarantee.", "For Texas SB 31, the required course is the free TMB course through MyTMB. Outside courses do not substitute for that specific requirement. Follow the Texas guide’s primary-source link to the official course instructions."] },
    ],
    faqs: [
      { question: "Does free CME count the same as paid CME?", answer: "Price does not establish acceptance. Check accreditation, content, timing and board approval for either a free or paid activity." },
      { question: "Can I finish every mandatory topic for free?", answer: "Availability varies. Check the current approved options for your degree and state. Confirm that each free course meets the specific requirement you need." },
      { question: "What if a course’s advertised price changed?", answer: "Use the provider’s current activity and checkout information. Report a stale listing so the catalog can be corrected; do not rely on an old price badge." },
    ], relatedStates: ["texas", "new-york", "california"],
  },
];
export function getNationalGuide(slug: string) { return nationalGuides.find((guide) => guide.slug === slug); }
