-- Generated by migrate dev during historical replay, then made compatible with
-- existing db-push databases that already use Prisma's shortened index name.
-- The original May migration requested a name PostgreSQL truncated to 63 bytes.
DO $$
BEGIN
  IF to_regclass('"UserRequirementCompletion_userId_mandatoryRequirementId_physici"') IS NOT NULL THEN
    ALTER INDEX "UserRequirementCompletion_userId_mandatoryRequirementId_physici"
      RENAME TO "UserRequirementCompletion_userId_mandatoryRequirementId_phy_key";
  ELSIF to_regclass('"UserRequirementCompletion_userId_mandatoryRequirementId_phy_key"') IS NULL THEN
    RAISE EXCEPTION 'Completion identity index is missing; inspect schema before baselining';
  END IF;
END $$;
